apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: tunnel-system
data:
  config.yml: |
    tunnel: 0186a39a-4077-4831-866c-f98bdeb42147
    ingress:
      - hostname: grafana.johnwalkers.com
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
      - hostname: k3s-lab.johnwalkers.com
        service: http://k3s-ui.k3s-ui.svc.cluster.local:80
      - hostname: johnwalkers.com
        service: http://k3s-ui.k3s-ui.svc.cluster.local:80
      - hostname: petunia.johnwalkers.com
        service: http://petunia-service.garden.svc.cluster.local
      - service: http_status:404